language: node_js
node_js:
- '8'
dist: trusty
os: linux
install:
- npm install
script:
- npm test
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: mt7/T3C3vnNiSLrHfDTqevDeplYoF011v18qhUPy8jT5weFHo0F1KBREuF0th0EZZgHuMKof7yw0foT53AXTA/Bsxm/1KafOoKTcT9xiCFCpQ15zjSHPxQ8ZaPv8gVcvD2E/2OzC5OtY024e0XgYP0VKMrxVi5UfpHRDYcsOPaFQWPIQ2mAhglmDZVD8BcDw19fPrD4TdeCfnFi+3y3Z5wJ1GC3PldEZc1Cw4uOMXfdaSYasA8m/OGfMZl3KCWSbYHbtFtlxe90AwBTli3JhoWKxSbDAGOntJqkXqecttDoxM1ZEFpSKkTnykPrZrxx0KxbrzeoRgvqjL6HwB0/teLlDEpmHEVW86JKqi2feCpOyeuU39TCkbj921BPabGyBpgv/XmmZ0i7qy21G4A2WpoOb5GTri0AP18pz5C+fo1Pf4PgEXRojZKwum7jdy4+nkhHRML+sUn/DXL8kl68IFmIqGrDOkIDN0YrlUVyjlbLdAqfUyKd4NJwPmZAYNmTw3xnG18BJYMeVxIs+uWEhy1MTxLVK7Mmf/qbNfciPsm7Y2hN2PC9hcC3+fp6VFH4L6BMG2dRUAirnW/DtYICNAdCp02hPKqGQDN+ZjP6waUYbPZKV0yBlzEVTsV8kxYf/y668MfX+WEYhhaKLWcuAxQp3po68Dhbv/taRQesutSI=
  app:
    master: greenpi-backend
    develop: greenpi-backend-dev
  skip_cleanup: true
