language: node_js
node_js:
- '8'
dist: trusty
os: linux
install:
- npm install
script:
- npm test
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: efPuFHgZM1QrKHWwG46gsy3ZWBAM/p8fkHVJ6FrrJ3GlMFdfbKPGqj6GmoRsAjFJlPnecublR4NaH5KU+qBqQ4fVk2/D27IoYs8+/G+BlpUJnKHxpOHvnq2tldwR4ZNrGA1XrrH/J63SHqBdCw1uzE2JG6GDSJbZl4hkXfBsGRnDQsb9nScdZzD3hiQMdvdA/KGM8708LXJjQ99GfKcHJsRva3Omwf4lm5/tw2oEbzzfLF73PdD8WCIAQBKOdZxm5szD++nBU9EbQT/xH5EbYIfHzYFPcXQiD5ARTnurKU29yUGEJGN1X23s6mA8nK9M0o9WYtWQ86fsQU5y9eDtUpHEXnUR3Zau3VmTWbNs/CVMkAVO2eM3UT2V+UuCOoKEZi5ZBmmY6QSUdTpOzPYu79ONnEEqHv6W1gCJGacKm2vhKl8Lpldmwkw8wOwKlNkb5tVaOnZQPkKn/3nv1s3km7F4b8a86lqN2PcggcVw1WelwWG4vKpnJQ7rIhkwOVqKurl+JeBzm9MaeAxEZ5ZoIYbKxg9paUzZq0gRZD5ldhZgbbQxGaK8dZ61m3CO1FXQ0qcC1UDosvzx+pUy2vGYBGJb1QnREk94j8UDkYVWqo/eniE0M1faiU9AA1XV1ERg0n36SWdbk98CXP9QR1Au5AqOSwzMlkfiKwQk/aYRz7k=
  app: greenpi-backend
  on:
    repo: nearlg/greenPi-backend
    branch: develop
  skip_cleanup: true
