language: node_js
node_js:
- '8'
dist: trusty
os: linux
install:
- npm install
script:
- npm test
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: nEldXDeVnhczEtpDfDtdA5C0Oyd0TTtwo75g8NW+HHSFY/UWQRftDHvoQdUHvGuX4JRbA2kAi0KI5kx3oByROZsEJ0KXVuCZf0uTzRq1kWbFaiuOOPV/XEo+19Ui8u5XrpBV1tzYcEG6UD2V7K0nq7MDJhkmdF+0PFhixbRT4EuDbqjXnBo8mjprSvumRD7z/JnhsZBvOROd3uUrO4fvVQsMmzH2Mj+4uC/PNu8arNZhhs1HVm4F4TSOtlnQVwDIJci3bJwxMLhWqpY+Axcms9FlEdpcsmjTDEJYoonmibTq85EydfPVYxtWtO1UtV/xTVJrGOXiq+8QE2yHw/39N8zcZdF8Yiu9x3enEC2fWeTet3HrnPnI9+oHM4h/8YnQDbZJy0EwA0eqjpYEbzxShvn931z2BfUuIsagFQUbkpW1h55H4aUFVNtkflmVsCU+SbYkRKxJhl2LW/WjkqEmssnTDkhKtAKy8qyrm88+3Sam0gvFWFiQi8N8QcADlP/SjADDSyaHxsHgkFiYeESQj8Pf5QJ917eoJsqqurxqE5CL56RhkYEJ1buLl9k8304hdb0BSSSc9tXCLW5DPyrSY9HBe7Iue5vIBHR3enH0lUUqNlDCU+K4prMwQ01hb9RUul0vTVyDPHLMngAqUXAKBIoOTJtF3aSaQgbqzipMyqg=
  app: greenpi-backend
  on:
    repo: nearlg/greenPi-backend
    branch: develop
  skip_cleanup: true
