name: Master push

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Intall node modules
      run: yarn
    - name: Test the code
      run: yarn test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: node_modules
        path: node_modules

  deploy:
    name: Build the Docker container
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: yarn build latest && yarn deploy latest
